# version: 2
# # dependencies:
# #   pre:
# #     - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
# # deployment:
# #   npm:
# #     tag: /v[0-9]+(\.[0-9]+)*/
# #         commands:
# #       - npm publish --access=public
# jobs:
#   # build:
#   #   docker:
#   #     - image: circleci/node:6.10
#   #   steps:
#   #     - checkout
#   #     - run:
#   #         name: Greeting
#   #         command: echo Hello, world.
#   #     - run:
#   #         name: Print the Current Time
#   #         command: date
#   one:
#     docker:
#       - image: circleci/node:6.10
#       steps:
#         - checkout
#         - run: echo "A first hello"
#         - run: sleep 25
#   two:
#     docker:
#       - image: circleci/node:6.10
#       steps:
#         - checkout
#         - run: echo "A second hello"
#         - run: sleep 15
# workflows:
#   version: 2
#   one_and_two:
#     jobs:
#       - one
#       - two


version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 25
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 15
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
