version: 2
defaults: &defaults
  working_directory: /tmp/react-input-primitives
  docker:
    - image: circleci/node:6.10
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Update Global Node Modules
          command: 'sudo npm install -g'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build for Production
          command: npm run dist
  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set up NPM Auth
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Publish Package
          command: npm publish --access=public

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish:
          requires:
            - build
